version: '3.3'

services:
  webapp:
    build:
      context: .
      dockerfile: ./ExampleWebApp/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__Sql=server=db;port=3306;database=webapp_dev;user=root;password=my-secret-dev-pw;
    depends_on:
      - db
volumes:
    db_data: {}