version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports: 
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-dev-pw
volumes:
    db_data: {}