version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports: 
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-dev-pw

  webapp:
    build:
      context: .
      dockerfile: ./ExampleWebApp/Dockerfile
    image: wordpress:latest
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__Sql=server=db;port=3306;database=webapp_dev;user=root;password=my-secret-dev-pw;
    depends_on:
      - db
volumes:
    db_data: {}